bug/urls.py
from django.urls import path

from . import views

app_name = "bug"
urlpatterns = [
    # ex: /bug/
    path("", views.index, name="index"),
    # ex: /bug/register/
    path("register/", views.register_bug, name="register"),
    # ex: /bug/bugs/
    path("bugs/", views.BugsView.as_view(), name="bugs"),
    # ex: /bug/1/
    path("<int:pk>/", views.DetailView.as_view(), name="detail")
]

capx/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("bug/", include("bug.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
]

bug/models.py
import datetime

from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models
from django.utils import timezone


# Create your models here.
class Bug(models.Model):
    FEATURE = "FEAT"
    ERROR = "ERR"
    FUNCTIONAL = "FUNC"
    LOGICAL = "LOGIC"
    WORKFLOW = "FLOW"
    USABILITY = "UIUX"
    SECURITY = "SEC"
    PERFORMANCE = "PERF"
    COMPATIBILITY = "COMP"
    UNIT = "UNIT"
    SYSTEM = "SYS"
    OUTOFBOUND = "OUT"
    BUG_TYPE_CHOICES = [
        (FEATURE, "New Feature"),
        (ERROR, "Error"),
        (FUNCTIONAL, "Functional"),
        (LOGICAL, "Logical"),
        (WORKFLOW, "Workflow"),
        (USABILITY, "Usability"),
        (SECURITY, "Security"),
        (PERFORMANCE, "Performance"),
        (COMPATIBILITY, "Compatibility"),
        (UNIT, "Unit Level"),
        (SYSTEM, "System Level"),
        (OUTOFBOUND, "Out of Bound"),
    ]

    TODO = "TODO"
    PLANNING = "PLAN"
    DESIGNING = "DESIGN"
    PROTOTYPING = "PROTO"
    WIP = "WIP"
    TESTING = "TEST"
    RNA = "RNA"
    STAGING = "STAGE"
    DEPLOYMENT = "DEPLOY"
    DONE = "DONE"
    STATUS_CHOICES = [
        (TODO, "To-Do"),
        (PLANNING, "Planning"),
        (DESIGNING, "Designing"),
        (PROTOTYPING, "Prototyping"),
        (WIP, "Work in Progress"),
        (TESTING, "Testing"),
        (RNA, "Review & Approval"),
        (STAGING, "Staging"),
        (DEPLOYMENT, "Deployment"),
        (DONE, "Done"),
    ]
    description = models.TextField(validators=[MinLengthValidator(25), MaxLengthValidator(200)])
    bug_type = models.CharField(max_length=5, choices=BUG_TYPE_CHOICES)
    report_date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=6, choices=STATUS_CHOICES)

    def __str__(self):
        return self.description

    def was_reported_recently(self):
        now = timezone.now()
        return now >= self.report_date >= now - datetime.timedelta(days=1)

bug/forms.py
from django import forms
from bug.models import Bug


class BugForm(forms.ModelForm):
    class Meta:
        model = Bug
        fields = ["description", "bug_type", "report_date", "status"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["description"] = forms.CharField(widget=forms.Textarea)
        self.fields["bug_type"] = forms.ChoiceField(choices=Bug.BUG_TYPE_CHOICES)
        self.fields["status"] = forms.ChoiceField(choices=Bug.STATUS_CHOICES)
        self.fields["report_date"] = forms.SplitDateTimeField(
                                        widget=forms.SplitDateTimeWidget
                                        (date_attrs={"type": "date"}, time_attrs={"type": "time"}))

bug/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils import timezone
from django.urls import reverse
from django.views import generic

from .forms import BugForm

from .models import Bug


# Create your views here.
def index(request):
    return render(request, "bug/index.html")


def register_bug(request):
    if request.method == "POST":
        form = BugForm(request.POST)
        if form.is_valid():
            bug = Bug.objects.create(**form.cleaned_data)
            bug.full_clean()
            bug.save()
            return HttpResponseRedirect(reverse("bug:bugs"))
    else:
        form = BugForm()
    return render(request, "bug/register.html", {"form": form})


class BugsView(generic.ListView):
    template_name = "bug/bugs.html"
    context_object_name = "bugs_list"

    def get_queryset(self) -> QuerySet[Any]:
        """Return all the registered bugs"""
        return Bug.objects.filter(report_date__lte=timezone.now()).order_by("-report_date")


class DetailView(generic.DetailView):
    model = Bug
    template_name = "bug/detail.html"
    context_object_name = "bug"

    def get_queryset(self) -> QuerySet[Any]:
        """
        Excludes any bugs that aren't reported yet
        """
        return Bug.objects.filter(report_date__lte=timezone.now())

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        bug = context["bug"]
        context["fields"] = {field.name: getattr(bug, f'get_{field.name}_display')()
                             if hasattr(bug, f'get_{field.name}_display')
                             else getattr(bug, field.name) for field in bug._meta.get_fields()}
        return context

bug/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Capacity Exchange bug app" />
        <title>Bug</title>
    </head>
    <body>
        <nav>
            <ul>
                <li><a href="{% url 'bug:index' %}">Home</a></li>
                <li><a href="{% url 'bug:register' %}">Register a bug</a></li>
                <li><a href="{% url 'bug:bugs' %}">View all bugs</a></li>
            </ul>
        </nav>
        {% block content %}{% endblock content%}
    </body>
</html>

bug/templates/bug/bugs.html
{% extends "base.html" %}

{% block content %}

<h2>Bugs</h2>

<ol>
{% for bug in bugs_list %}
    <li>
        <a href="{% url 'bug:detail' bug.id %}">{{ bug.description }}</a>
    </li>
{% empty %}
    <li>No bugs are registered.</li>
{% endfor %}
</ol>

{% endblock content%}

bug/templates/bug/detail.html
{% extends "base.html" %}

{% block content %}

<h2>Bug {{ bug.id }}</h2>

<ol>
    {% for name, value in fields.items %}
        <li>{{ name }} - {{ value }}</li>
    {% endfor %}
</ol>

{% endblock content %}

bug/templates/bug/index.html
{% extends "base.html" %}

{% block content %}

<header>
    <h1>Bug</h1>
</header>

<main>
    <p>"Hello, world. You're at the bug index."</p>
</main>

{% endblock content%}

bug/templates/bug/register.html
{% extends "base.html" %}

{% block content %}

<form action="{% url 'bug:register' %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.bug_type.errors }}
        {{ form.bug_type.label_tag }}
        {{ form.bug_type }}
    </div>
    <div class="fieldWrapper">
        {{ form.status.errors }}
        {{ form.status.label_tag }}
        {{ form.status }}
    </div>
    <div class="fieldWrapper">
        {{ form.description.errors }}
        {{ form.description.label_tag }}
        {{ form.description }}
    </div>
    <div class="fieldWrapper">
        {{ form.report_date.errors }}
        {{ form.report_date.label_tag }}
        {{ form.report_date }}
    </div>
    <input type="submit" value="Register" />
</form>

{% endblock content %}